name: Doxygen Documentation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Doxygen
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen graphviz

    - name: Ensure docs directory exists
      run: mkdir -p docs

    - name: Generate Maven Site
      run: mvn site

    - name: Organize docs folder
      run: |
        mkdir -p docs
        rm -rf docs/site
        mkdir -p docs/site
        cp -r target/site/* docs/site/
        rm -rf docs/doxygen
        mkdir -p docs/doxygen
        cp -r target/html/* docs/doxygen/

        